version: "3"
services:
  mysql:
    image: mysql
    container_name: test-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
      
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql
  postgres:
    image: postgres
    container_name: test-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - /var/lib/postgresql/datadir
    ports:
      - 5432:5432
